### ISSUE TITLE
Range-Requests for OCFL files

### ISSUE THREAD

**Issue by rsteph-de** [OCFL/ocfl-java#118]
There are different use cases where it would be helpful, if the OCFL Java API supports RangeRequests:
- download of very large files
- mulitpart downloads / resume download on error
- retrieve parts of files 
  - Cover Images / first page from PDF files
  - get single files from TAR archive or uncompressed ZIP
 
Currently we can only get the whole input stream, skip first bytes and close early, after the request is fulfilled.
But most of the implementations support RangeRequest directly (like RandomAccessFiles in Java or Range-Requests for S3Objects).

It would be very useful if the OCFL Java API could be enhanced with methods to request ranges of files and pass them through to the underlying implementations.

**Comment by pwinckles** [comment]
@rsteph-de Thanks for filing this issue. I haven't had a chance to investigate the options yet, but hope to later this week and will then get back to you.

**Comment by pwinckles** [comment]
@rsteph-de Sorry, I finally had time to look at this a little. What do you think about the following:

1. Add a new method to `OcflFileRetriever` with the signature `InputStream retrieveRange(Long start, Long end)` that can be used to execute a range request
2. Add a new method to `OcflObjectVersionFile` with the signature `InputStream getRange(Long start, Long end)` that calls the above method

Would this work for you?

I would use the values provided to construct a range string like in the [rfc](https://www.rfc-editor.org/rfc/rfc9110.html#name-byte-ranges), but don't really want to accept a range string because I need to make this work for a `RandomAccessFile` too.

**Comment by Mewel** [comment]
@pwinckles Looks good to me

**Comment by rsteph-de** [comment]
@pwinckles Thank you for starting to work on this issue. I discussed your suggestion with Mewel who is going to use this feature to implement range requests on OCFL files in our repository framework. Your solution will work for us.

**Comment by pwinckles** [comment]
Great. I hope to be able to get a PR ready for you all to review within a week or so.

**Comment by pwinckles** [comment]
@rsteph-de @Mewel I just posted a PR: https://github.com/OCFL/ocfl-java/pull/120

Please let me know if it works for you.

**Comment by pwinckles** [comment]
@rsteph-de @Mewel This will be released in https://github.com/OCFL/ocfl-java/releases/tag/v2.2.1. However, the publish to Maven Central is currently failing, and it's unclear why. I'll try again tomorrow.

**Comment by pwinckles** [comment]
@rsteph-de @Mewel the publish worked today. It should be available in central tomorrow. Please open need tickets if you need anything else.
